env:
  matrix:
    - PYTHON_VERSION="3.6.0"
    - PYTHON_VERSION="3.6.1"
    - PYTHON_VERSION="3.6.2"
    - PYTHON_VERSION="3.6.3"
    - PYTHON_VERSION="3.6.4"
    - PYTHON_VERSION="3.6.5"
    - PYTHON_VERSION="3.6.6"
    - PYTHON_VERSION="3.7.0"
    - PYTHON_VERSION="3.7.1"
    - PYTHON_VERSION="3.7.2"

language: generic
sudo: false

os:
  - linux
  - osx

matrix:
  fast_finish: true

install:
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python -VV
  - pip --version
  - pip install pylint coverage coveralls

script:
  - coverage run setup.py test && python3 setup.py install
  - domain2idna -d аррӏе.com
  - domain2idna -f .travis/list_of_domain
  - domain2idna -f .travis/list_of_domain -o list_of_domain_converted
  - echo "Tests linting " && pylint tests/*.py && echo "domain2idna linting" && pylint domain2idna

after_success:
  - coveralls

notifications:
  on_success: change
  on_failure: always
