env:
  global:
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble

language:       python

python:
  - "3.6"
  - "3.6.5"

os:
  - linux
  - osx

matrix:
  fast_finish:  true

install:
  - pip3 install --upgrade pip
  - pip3 install pylint coverage coveralls

script:
  - coverage run setup.py test && python3 setup.py install
  - domain2idna -d аррӏе.com
  - domain2idna .travis/list_of_domain
  - echo "Tests linting " && pylint tests/*.py && echo "domain2idna linting" && pylint domain2idna

after_success:
- coveralls

notifications:
  on_success:   change
  on_failure:   always