jobs:
  include:
    - stage: "Tests"
      os: linux
      dist: bionic
      name: "Test with Python 3.8.0 under Ubuntu 18.04 (Bionic Beaver)"
      env:
        - PYTHON_VERSION="3.8.0"
        - TOXENV="py38"
      language: generic
    - os: osx
      osx_image: xcode11.2
      name: "Test with Python 3.7.5 under macOS 10.14 (Mojave)"
      env:
        - PYTHON_VERSION="3.8.0"
        - TOXENV="py38"
      language: generic
    - os: linux
      dist: bionic
      name: "Test with Python 3.7.5 under Ubuntu 18.04 (Bionic Beaver)"
      env:
        - PYTHON_VERSION="3.7.5"
        - TOXENV="py37"
      language: generic
    - os: osx
      osx_image: xcode11.2
      name: "Test with Python 3.7.5 under macOS 10.14 (Mojave)"
      env:
        - PYTHON_VERSION="3.7.5"
        - TOXENV="py37"
      language: generic
    - os: linux
      dist: bionic
      name: "Test with Python 3.7.4 under Ubuntu 18.04 (Bionic Beaver)"
      env:
        - PYTHON_VERSION="3.7.4"
        - TOXENV="py37"
      language: generic
    - os: osx
      osx_image: xcode11.2
      name: "Test with Python 3.7.4 under macOS 10.14 (Mojave)"
      env:
        - PYTHON_VERSION="3.7.4"
        - TOXENV="py37"
      language: generic
    - os: linux
      dist: bionic
      name: "Test with Python 3.6.9 under Ubuntu 18.04 (Bionic Beaver)"
      env:
        - PYTHON_VERSION="3.6.9"
        - TOXENV="py36"
      language: generic
    - os: osx
      osx_image: xcode11.2
      name: "Test with Python 3.6.9 under macOS 10.14 (Mojave)"
      env:
        - PYTHON_VERSION="3.6.9"
        - TOXENV="py37"
      language: generic
    - os: linux
      dist: bionic
      name: "Test with Python 3.6.8 under Ubuntu 18.04 (Bionic Beaver)"
      env:
        - PYTHON_VERSION="3.6.8"
        - TOXENV="py37"
      language: generic
    - os: osx
      osx_image: xcode11.2
      name: "Test with Python 3.6.8 under macOS 10.14 (Mojave)"
      env:
        - PYTHON_VERSION="3.6.8"
        - TOXENV="py37"
      language: generic
    - stage: "Deployements"
      os: linux
      dist: bionic
      name: "Deployement to PyPi"
      env:
        - PYTHON_VERSION="3.8.0"
        - TOXENV="py38"
      language: generic
      script:
        - echo "Hello, World!"
      after_success:
        - echo "Hello, World!"
      deploy:
        provider: pypi
        user: funilrys
        password:
          secure: 3tnxkvpwsRbmHIiRxeQ2/at5SkJb17dKzkvkdNhxsY9LP8EvspH5ixYiVvnC3kxRY90oPvcgCEAKZJRwFnVJTP7kO++GF6v3cnWc9yGpCJtLvOIS20OSjm32uuYTXTBavKfb+1vU/U58dAI+K8Fg7MBj+7gQM2rn6SUbmZpMZvNrAR/dJYaSlAASiKaukAE4SBu9HP6Q9Ic8qV8glpOeKSwObHkwcKMZZFHI8JfHKKSTzVLfH4RdWTHNnTpOUcddHE4Fh68oq13iJT8QAZDK1jnUIbryZOvs7cURM7Qtu0hiDRvG8UEWZ1WfWV6UNhewvHmpxYvDr88BBKZwqBCZawlfXjKjYHqMftMuQb6+O6UuVQFSN7NLBDRuW9qhLXGgF3/bb/Y5PeZmMbkLkDip5ywGF/Li6YTs6pP1q/+rAizHh53qBNWcD9O9Zgd/fNYt2vP0vFTzBGoD4cv9WQtPQWCGFlV6Kgjz+RS7FSSJOwWM8CO5L42I5oHlCJzJ1tWVoTvBEmx7hXa02uFyVIli/+rPQJtA4FgKNXNTOU+JzTBMg7jqRgT1soR3ZXrBraPGawpnrUSi1ayZ0WlNi4b8UECvwq4Wsm+wRU10B0s8yNe4a3RTGU5lOzR3D1DyXGJLOBVJyPHvZRMaXZGZx6FdYa1jFGhbTr+rS8EIzsWwxLI=
        distributions: sdist bdist_wheel
        skip_existing: true
        on:
          all_branches: true
          condition: "${TRAVIS_BRANCH} =~ ^master$"

matrix:
  fast_finish: true

install:
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python -VV
  - pip --version
  - pip install pylint coverage coveralls PyYAML pylint coverage coveralls codacy-coverage tox-current-env
  - pip install -e .

script:
  - pylint domain2idna
  - pylint tests
  - coverage run setup.py test
  - coverage xml
  - domain2idna -d аррӏе.com
  - domain2idna -f .travis/list_of_domain
  - domain2idna -f .travis/list_of_domain -o list_of_domain_converted
  - cat list_of_domain_converted

after_success:
  - python-codacy-coverage -r coverage.xml
  - coveralls

notifications:
  on_success: change
  on_failure: always
